"""initial migration

Revision ID: 15f66df61ccb
Revises: None
Create Date: 2015-01-11 23:45:23.912000

"""

# revision identifiers, used by Alembic.
revision = '15f66df61ccb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
